# Importing and converting code into required format

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("C:/Users/vineeth/Downloads/titanic.csv")

In [12]:
data

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Cabin Embarked
0           0       3    male  34.5      0      0    7.8292   NaN        Q
1           1       3  female  47.0      1      0    7.0000   NaN        S
2           0       2    male  62.0      0      0    9.6875   NaN        Q
3           0       3    male  27.0      0      0    8.6625   NaN        S
4           1       3  female  22.0      1      1   12.2875   NaN        S
..        ...     ...     ...   ...    ...    ...       ...   ...      ...
413         0       3    male   NaN      0      0    8.0500   NaN        S
414         1       1  female  39.0      0      0  108.9000  C105        C
415         0       3    male  38.5      0      0    7.2500   NaN        S
416         0       3    male   NaN      0      0    8.0500   NaN        S
417         0       3    male   NaN      1      1   22.3583   NaN        C

[418 rows x 9 columns]

In [ ]:
## Sir i removed some catagerical data like Name, Ticket, PassengerId then printed data later i tried to remove cabin and Age 
##from previous data but this step went wrong and now i printed final data

In [13]:
data = data.drop(["Cabin", "Age"], axis = 1)

In [14]:
data

Survived  Pclass     Sex  SibSp  Parch      Fare Embarked
0           0       3    male      0      0    7.8292        Q
1           1       3  female      1      0    7.0000        S
2           0       2    male      0      0    9.6875        Q
3           0       3    male      0      0    8.6625        S
4           1       3  female      1      1   12.2875        S
..        ...     ...     ...    ...    ...       ...      ...
413         0       3    male      0      0    8.0500        S
414         1       1  female      0      0  108.9000        C
415         0       3    male      0      0    7.2500        S
416         0       3    male      0      0    8.0500        S
417         0       3    male      1      1   22.3583        C

[418 rows x 7 columns]

In [16]:
data['Sex'].unique()

array(['male', 'female'], dtype=object)

In [17]:
data["Sex"] = data["Sex"].map({"male":1,"female":0})

In [18]:
data['Sex'].unique()

array([1, 0], dtype=int64)

In [22]:
data.head()

Survived  Pclass  Sex  SibSp  Parch     Fare Embarked
0         0       3    1      0      0   7.8292        Q
1         1       3    0      1      0   7.0000        S
2         0       2    1      0      0   9.6875        Q
3         0       3    1      0      0   8.6625        S
4         1       3    0      1      1  12.2875        S

In [15]:
data['Embarked'].unique()

array(['Q', 'S', 'C'], dtype=object)

In [21]:
data['Embarked'].value_counts()

S    270
C    102
Q     46
Name: Embarked, dtype: int64

In [19]:
a = pd.get_dummies(data['Embarked'] , drop_first=True)

In [20]:
a.head()

Q  S
0  1  0
1  0  1
2  1  0
3  0  1
4  0  1

In [26]:
data = pd.concat([data , a],axis = 1)

In [27]:
data

Survived  Pclass  Sex  SibSp  Parch      Fare  Q  S
0           0       3    1      0      0    7.8292  1  0
1           1       3    0      1      0    7.0000  0  1
2           0       2    1      0      0    9.6875  1  0
3           0       3    1      0      0    8.6625  0  1
4           1       3    0      1      1   12.2875  0  1
..        ...     ...  ...    ...    ...       ... .. ..
413         0       3    1      0      0    8.0500  0  1
414         1       1    0      0      0  108.9000  0  0
415         0       3    1      0      0    7.2500  0  1
416         0       3    1      0      0    8.0500  0  1
417         0       3    1      1      1   22.3583  0  0

[418 rows x 8 columns]

In [40]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
SibSp       0
Parch       0
Fare        1
Q           0
S           0
dtype: int64

In [41]:
data["Fare"].unique()

array([  7.8292,   7.    ,   9.6875,   8.6625,  12.2875,   9.225 ,
         7.6292,  29.    ,   7.2292,  24.15  ,   7.8958,  26.    ,
        82.2667,  61.175 ,  27.7208,  12.35  ,   7.225 ,   7.925 ,
        59.4   ,   3.1708,  31.6833,  61.3792, 262.375 ,  14.5   ,
        61.9792,  30.5   ,  21.6792,  31.5   ,  20.575 ,  23.45  ,
        57.75  ,   8.05  ,   9.5   ,  56.4958,  13.4167,  26.55  ,
         7.85  ,  13.    ,  52.5542,  29.7   ,   7.75  ,  76.2917,
        15.9   ,  60.    ,  15.0333,  23.    , 263.    ,  15.5792,
        29.125 ,   7.65  ,  16.1   ,  13.5   ,   7.725 ,  21.    ,
         7.8792,  42.4   ,  28.5375, 211.5   ,  25.7   ,  15.2458,
       221.7792,  10.7083,  14.4542,  13.9   ,   7.775 ,  52.    ,
         7.7958,  78.85  ,   7.8542,  55.4417,   8.5167,  22.525 ,
         7.8208,   8.7125,  15.0458,   7.7792,  31.6792,   7.2833,
         6.4375,  16.7   ,  75.2417,  15.75  ,   7.25  ,  23.25  ,
        28.5   ,  25.4667,  46.9   , 151.55  ,  18.    ,  51.8

In [42]:
data = data.drop(["Fare"], axis = 1)

In [43]:
data

Survived  Pclass  Sex  SibSp  Parch  Q  S
0           0       3    1      0      0  1  0
1           1       3    0      1      0  0  1
2           0       2    1      0      0  1  0
3           0       3    1      0      0  0  1
4           1       3    0      1      1  0  1
..        ...     ...  ...    ...    ... .. ..
413         0       3    1      0      0  0  1
414         1       1    0      0      0  0  0
415         0       3    1      0      0  0  1
416         0       3    1      0      0  0  1
417         0       3    1      1      1  0  0

[418 rows x 7 columns]

In [44]:
X = data.iloc[ : , 1:]
y = data.iloc[ : , 0]

In [45]:
X

Pclass  Sex  SibSp  Parch  Q  S
0         3    1      0      0  1  0
1         3    0      1      0  0  1
2         2    1      0      0  1  0
3         3    1      0      0  0  1
4         3    0      1      1  0  1
..      ...  ...    ...    ... .. ..
413       3    1      0      0  0  1
414       1    0      0      0  0  0
415       3    1      0      0  0  1
416       3    1      0      0  0  1
417       3    1      1      1  0  0

[418 rows x 6 columns]

In [46]:
y

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    1
415    0
416    0
417    0
Name: Survived, Length: 418, dtype: int64

# Train and Test

In [47]:
from sklearn.model_selection import train_test_split


In [48]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.33 , random_state=11)

In [49]:
X_train

Pclass  Sex  SibSp  Parch  Q  S
309       3    0      1      0  0  1
105       3    1      0      0  0  1
250       2    0      1      2  0  1
416       3    1      0      0  0  1
203       2    0      1      1  0  1
..      ...  ...    ...    ... .. ..
337       3    1      0      2  0  0
91        3    1      0      0  0  1
80        3    1      1      1  0  0
191       1    1      0      0  0  1
409       3    0      1      1  0  1

[280 rows x 6 columns]

In [50]:
y_train

309    1
105    0
250    1
416    0
203    1
      ..
337    0
91     0
80     0
191    0
409    1
Name: Survived, Length: 280, dtype: int64

# KNN

In [51]:
from sklearn.neighbors import KNeighborsClassifier

In [52]:
reg = KNeighborsClassifier()

In [53]:
reg.fit(X_train,y_train)

KNeighborsClassifier()

# accuracy for train data

In [54]:
reg.score(X_train,y_train)

0.9964285714285714

In [55]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [57]:
y_train_pred = reg.predict(X_train)

In [58]:
confusion_matrix(y_train,y_train_pred)

array([[179,   0],
       [  1, 100]], dtype=int64)

In [59]:
X_train.shape

(280, 6)

In [60]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       179
           1       1.00      0.99      1.00       101

    accuracy                           1.00       280
   macro avg       1.00      1.00      1.00       280
weighted avg       1.00      1.00      1.00       280



# accuracy for train data

In [61]:
reg.score(X_test,y_test)

0.9565217391304348

In [62]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [64]:
y_test_pred = reg.predict(X_test)

In [65]:
confusion_matrix(y_test,y_test_pred)

array([[83,  4],
       [ 2, 49]], dtype=int64)

In [66]:
X_test.shape

(138, 6)

In [67]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       179
           1       1.00      0.99      1.00       101

    accuracy                           1.00       280
   macro avg       1.00      1.00      1.00       280
weighted avg       1.00      1.00      1.00       280



# NAVIE BAY'S

In [68]:
from sklearn.naive_bayes import GaussianNB

In [69]:
reg = GaussianNB()

In [70]:
reg.fit(X_train,y_train)

GaussianNB()

In [71]:
y_train_pred = reg.predict(X_train)

In [76]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [77]:
accuracy_score(y_train,y_train_pred)

1.0

In [78]:
reg.score(X_train,y_train)

1.0

In [79]:
confusion_matrix(y_train,y_train_pred)

array([[179,   0],
       [  0, 101]], dtype=int64)

In [80]:
print(classification_report(y_train,y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       179
           1       1.00      1.00      1.00       101

    accuracy                           1.00       280
   macro avg       1.00      1.00      1.00       280
weighted avg       1.00      1.00      1.00       280



# Logistic Regression

In [81]:
from sklearn.linear_model import LogisticRegression

In [83]:
model=LogisticRegression(multi_class='multinomial')
model.fit(X_train,y_train)

LogisticRegression(multi_class='multinomial')

In [84]:
y_pred=model.predict(X_test)
y_pred

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1], dtype=int64)

In [85]:
y_test

262    1
347    1
392    0
74     1
237    0
      ..
98     1
196    0
286    0
210    0
216    1
Name: Survived, Length: 138, dtype: int64

In [86]:
model.score(X_train,y_train)

1.0

In [87]:
model.score(X_test,y_test)

1.0

In [88]:
from sklearn.metrics import confusion_matrix

In [89]:
confusion_matrix(y_test,y_pred)

array([[87,  0],
       [ 0, 51]], dtype=int64)

# Decision Tree

In [90]:
from sklearn.tree import DecisionTreeClassifier

In [91]:
model=DecisionTreeClassifier()
model.fit(X,y)

DecisionTreeClassifier()

In [93]:
model.score(X,y)

1.0